package View;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author lucia
 */
public class frmUser extends JFrame {

    /**
     * Creates new form frmUser
     */

    private JButton jButton1;
    private Point defaultFrameSize;
    private Point defaultRegistrarPosition;
    private JTextField jtfPuesto;
    private JLabel jlbApellidos;
    private JLabel jlbContrasena;
    private JLabel jlbFondo;
    private JLabel jlbID;
    private JLabel jlbIconUser;
    private JLabel jlbIniciarSesion;
    private JLabel jlbNombre;
    private JLabel jlbPuesto;
    private JLabel jlbRegistrase;
    private JLabel jlbTelefono;
    private JPasswordField jpfContrasena;
    private JTextField jtfApellidos;
    private JTextField jtfID;
    private JTextField jtfNombre;
    private JTextField jtfTelefono;
    public frmUser() {
        initComponents();
    }

    @Override
    public Image getIconImage() {
        //Se elige de los recursos de imágenes, la que se utilizará como icono
        Image valorRetorno = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/user.png"));
        return valorRetorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        defaultFrameSize = new Point(400,621);
        defaultRegistrarPosition = new Point(140,590);

        jButton1 = new JButton();
        jlbIconUser = new JLabel();
        jlbID = new JLabel();
        jlbNombre = new JLabel();
        jtfID = new JTextField();
        jpfContrasena = new JPasswordField();
        jlbApellidos = new JLabel();
        jlbTelefono = new JLabel();
        jlbContrasena = new JLabel();
        jtfNombre = new JTextField();
        jtfApellidos = new JTextField();
        jtfTelefono = new JTextField();
        jlbRegistrase = new JLabel();
        jlbIniciarSesion = new JLabel();
        jlbPuesto = new JLabel();
        jtfPuesto = new JTextField();
        jlbFondo = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setLayout(null);

        jButton1.setIcon(new ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton1.setBounds(350, 0,50,50);
        add(jButton1);

        jlbIconUser.setIcon(new ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jlbIconUser.setBounds(130,80, jlbIconUser.getMinimumSize().width, jlbIconUser.getMinimumSize().height);
        add(jlbIconUser);

        jlbID.setBackground(new Color(204, 255, 153));
        jlbID.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jlbID.setText(" ID:");
        jlbID.setBounds(45, 280, 30, 20);
        add(jlbID);

        jlbNombre.setBackground(new Color(204, 255, 153));
        jlbNombre.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jlbNombre.setText(" Nombre:");
        jlbNombre.setBounds(45, 380, jlbNombre.getMinimumSize().width, 20);
        add(jlbNombre);

        jtfID.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        jtfID.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jtfID.setBounds(155,280,200,jtfID.getMinimumSize().height);
        add(jtfID);

        jpfContrasena.setFont(new Font("Tahoma", Font.PLAIN, 14)); // NOI18N
        jpfContrasena.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jpfContrasena.setBounds(155,330,200,jpfContrasena.getPreferredSize().height);
        add(jpfContrasena);

        jlbApellidos.setBackground(new Color(204, 255, 153));
        jlbApellidos.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jlbApellidos.setText(" Apellido:");
        jlbApellidos.setBounds(50,430,jlbApellidos.getPreferredSize().width,20);
        add(jlbApellidos);

        jlbTelefono.setBackground(new Color(204, 255, 153));
        jlbTelefono.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jlbTelefono.setText(" Teléfono:");
        jlbTelefono.setBounds(50,480,jlbTelefono.getPreferredSize().width,20);
        add(jlbTelefono);

        jlbContrasena.setBackground(new Color(204, 255, 153));
        jlbContrasena.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        jlbContrasena.setText(" Contraseña:");
        jlbContrasena.setBounds(45,330,jlbContrasena.getPreferredSize().width,20);
        add(jlbContrasena);

        jtfNombre.setFont(new Font("Tahoma", Font.PLAIN, 14)); // NOI18N
        jtfNombre.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jtfNombre.setBounds(155,480,200,jtfNombre.getPreferredSize().height);
        add(jtfNombre);

        jtfApellidos.setFont(new Font("Tahoma", Font.PLAIN, 14)); // NOI18N
        jtfApellidos.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jtfApellidos.setBounds(155,380,200,jtfApellidos.getPreferredSize().height);
        add(jtfApellidos);

        jtfTelefono.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        jtfTelefono.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        jtfTelefono.setBounds(155, 430, 200, jtfTelefono.getPreferredSize().height);
        add(jtfTelefono);

        jlbRegistrase.setBackground(new Color(255, 153, 153));
        jlbRegistrase.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jlbRegistrase.setText(" Registrarse");
        jlbRegistrase.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jlbRegistrase.setBounds(140,590,jlbRegistrase.getPreferredSize().width,20);
        add(jlbRegistrase);

        jlbIniciarSesion.setBackground(new Color(204, 255, 153));
        jlbIniciarSesion.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jlbIniciarSesion.setText("Iniciar sesión");
        jlbIniciarSesion.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Dimension iniciarSesion = jlbIniciarSesion.getPreferredSize();
        jlbIniciarSesion.setBounds(140,230,iniciarSesion.width,iniciarSesion.height);
        add(jlbIniciarSesion);

        jlbPuesto.setBackground(new Color(204, 255, 153));
        jlbPuesto.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jlbPuesto.setText(" Puesto: ");
        jlbPuesto.setBounds(45,530,jlbPuesto.getPreferredSize().width,20);
        add(jlbPuesto);

        jtfPuesto.setFont(new Font("Tahoma", Font.PLAIN, 14)); // NOI18N
        jtfPuesto.setBounds(155,530,200, jtfPuesto.getPreferredSize().height);
        add(jtfPuesto);

        jlbFondo.setIcon(new ImageIcon(getClass().getResource("/Imagenes/fondoMulticolor.jpg"))); // NOI18N
        jlbFondo.setBounds(0,0,jlbFondo.getMinimumSize().width,620);
        add(jlbFondo);

        setSize(new Dimension(400, 621));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUser().setVisible(true);
            }
        });
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JTextField getJtfPuesto() {
        return jtfPuesto;
    }

    public JLabel getJlbApellidos() {
        return jlbApellidos;
    }

    public JLabel getJlbContrasena() {
        return jlbContrasena;
    }

    public JLabel getJlbFondo() {
        return jlbFondo;
    }

    public JLabel getJlbID() {
        return jlbID;
    }

    public JLabel getJlbIconUser() {
        return jlbIconUser;
    }

    public JLabel getJlbIniciarSesion() {
        return jlbIniciarSesion;
    }

    public JLabel getJlbNombre() {
        return jlbNombre;
    }

    public JLabel getJlbPuesto() {
        return jlbPuesto;
    }

    public JLabel getJlbRegistrase() {
        return jlbRegistrase;
    }

    public JLabel getJlbTelefono() {
        return jlbTelefono;
    }

    public JPasswordField getJpfContrasena() {
        return jpfContrasena;
    }

    public JTextField getJtfApellidos() {
        return jtfApellidos;
    }

    public JTextField getJtfID() {
        return jtfID;
    }

    public JTextField getJtfNombre() {
        return jtfNombre;
    }

    public JTextField getJtfTelefono() {
        return jtfTelefono;
    }

    public Point getDefaultFrameSize() {
        return defaultFrameSize;
    }

    public Point getDefaultRegistrarPosition() {
        return defaultRegistrarPosition;
    }
}

